### PR TITLE
Homework28

### PR DESCRIPTION
**Pull request by cinck**
Hi!

Please check my homework.
Tasks are marked \<HW28\> in comments of JS file.

### CODE REVIEW

**Comment by cinck** [comment]
Can you advise what to do if bootstrap overrides my CSS values in table formatting?

**Comment by acman** [comment]
> Can you advise what to do if bootstrap overrides my CSS values in table formatting?

do more specific styling like .someClass > p > span. It will override bootstrap styles or probably, add some class to table - it will be enough

**Review by acman — APPROVED** [review]
GJ!

**Comment by cinck** [comment]
> > Can you advise what to do if bootstrap overrides my CSS values in table formatting?
> 
> do more specific styling like .someClass > p > span. It will override bootstrap styles or probably, add some class to table - it will be enough

Well I've noticed that it depends on css links order in HTML. The latest one in code overrides previous if they have styles for same objects.

**Pull request merged**
